name: Feature Request
description: Suggest an idea to help reduce wait times and improve efficiency at the hospital.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your ideas for making Easpataal better.

  - type: dropdown
    id: app
    attributes:
      label: Which app is this feature for?
      options:
        - main (Staff-facing application)
        - patient (Patient-facing application)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What is the problem you are trying to solve?
      description: Is your feature request related to a problem? Please describe the challenge you or others face. (e.g., "As a nurse, it's difficult to track patient token status, leading to confusion.")
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What is your proposed solution?
      description: Describe the feature you'd like to see and how it would solve the problem.
      placeholder: I would like to see a dashboard where I can view all active tokens and their current status in real-time.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered any alternative solutions or features?
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.