name: CI/CD Pipeline - Main

on:
  push:
    paths:
      - 'main/**'
  pull_request:
    paths:
      - 'main/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./main

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: main/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:ci

      - name: Upload build status
        uses: actions/upload-artifact@v4
        with:
          name: build-status-main
          path: main/build-status.txt